logging:
  level:
    root: info

server:
  port: 8080
  shutdown: graceful
  error: # default error attribute for prod profile
    include-exception: false # Include the "exception" attribute.
    include-stacktrace: never # When to include a "stacktrace" attribute. possible value is 'always, never, on_param'
    whitelabel.enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.time_zone: Asia/Seoul
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  packages-to-scan: com.example

eco:
  datasource:
    read:
      hikari:
        username: # SPRING_DATASOURCE_READ_HIKARI_USERNAME
        password: # SPRING_DATASOURCE_READ_HIKARI_PASSWORD
        jdbc-url: # SPRING_DATASOURCE_READ_HIKARI_JDBC_URL
        auto-commit: false
    write:
      hikari:
        username: # SPRING_DATASOURCE_WRITE_HIKARI_USERNAME
        password: # SPRING_DATASOURCE_WRITE_HIKARI_PASSWORD
        jdbc-url: # SPRING_DATASOURCE_WRITE_HIKARI_JDBC_URL
        auto-commit: false